import { Button } from "@heroui/react";
import type { WorkOrder } from "../types/workOrder";
import { Icon } from "../components/Icon";
import { PhotoTile } from "../components/PhotoTile";
import { SubHeader } from "../components/Navigation";
import { StatusBadge } from "../components/WorkOrderList";

type DateProps = { date: string; onDateChange: (value: string) => void };

export function PreparePage({ orders, activeOrder, historyFileName, libraryFileName, date, onDateChange, onBack, onSelectOrder, onPickHistoryFile, onPickLibraryFile, onNext }: { orders: WorkOrder[]; activeOrder: WorkOrder; historyFileName: string; libraryFileName: string; onBack: () => void; onSelectOrder: (id: string) => void; onPickHistoryFile: (file: File | null) => void; onPickLibraryFile: (file: File | null) => void; onNext: () => void } & DateProps) {
  return <><SubHeader title="准备照片" date={date} onDateChange={onDateChange} onBack={onBack} /><div className="stepper"><span className="current">1</span><i /><span>2</span><i /><span>3</span><em>照片准备</em></div><section className="prepare-tabs">{orders.map((order, index) => <button key={`${order.id}-${index}`} onClick={() => onSelectOrder(order.id)} className={order.id === activeOrder.id ? "active" : ""}>{order.resident}<small>{order.unit}</small></button>)}</section><section className="prep-order"><p className="eyebrow">{activeOrder.id}</p><h2>{activeOrder.address}</h2><span>{activeOrder.resident} · {activeOrder.unit} · {activeOrder.time}</span></section><section className="section-block"><div className="section-heading"><div><h3>历史到访照片</h3><p>选择一张已核验的“到访不遇”图片</p></div><b>必选</b></div><label className="file-picker"><span>{historyFileName || "选择历史照片"}</span><input type="file" accept="image/*" onChange={(event) => onPickHistoryFile(event.target.files?.[0] ?? null)} /></label></section><section className="section-block"><div className="section-heading"><div><h3>本机图库补图</h3><p>选择一张现场环境图片</p></div><b>必选</b></div><label className="file-picker"><span>{libraryFileName || "选择本机补图"}</span><input type="file" accept="image/*" onChange={(event) => onPickLibraryFile(event.target.files?.[0] ?? null)} /></label></section><div className="page-action"><Button className="primary-button" onPress={onNext}>下一步：确认提交 <Icon name="chevron" size={17} /></Button></div></>;
}

export function ConfirmPage({ orders, reason, date, onDateChange, onBack, onReasonChange, onStart }: { orders: WorkOrder[]; reason: string; onBack: () => void; onReasonChange: (value: string) => void; onStart: () => void } & DateProps) {
  return <><SubHeader title="确认提交" date={date} onDateChange={onDateChange} onBack={onBack} /><div className="stepper"><span>1</span><i /><span className="current">2</span><i /><span>3</span><em>确认信息</em></div><section className="confirm-hero"><span>本次将串行处理</span><strong>{orders.length}</strong><b>个到访不遇工单</b><p>每单上传两张照片后关闭工单，再写入流转日志。</p></section><section className="confirm-list">{orders.map((order, index) => <article key={`${order.id}-${index}`}><div><b>{order.resident} · {order.unit}</b><span>{order.id}</span></div><div className="mini-photos"><PhotoTile label="历史" tone="gold" /><PhotoTile label="补图" tone="green" /></div></article>)}</section><section className="form-card"><label>流转人<input value="当前操作员" readOnly /></label><label>流转原因<input value={reason} onChange={(event) => onReasonChange(event.target.value)} /></label><label>备注<textarea defaultValue="现场到访未遇，门口有居住痕迹。" /></label></section><p className="safety-note">提交后不可撤销。关闭成功但日志失败时，系统只会补发日志，不会重复关闭。</p><div className="page-action"><Button className="primary-button" onPress={onStart}>开始串行提交 <Icon name="play" size={16} /></Button></div></>;
}

export function RunningPage({ total, current, message, running, paused, date, onDateChange, onBack, onTogglePause, onFinish }: { total: number; current: number; message: string; running: boolean; paused: boolean; onBack: () => void; onTogglePause: () => void; onFinish: () => void } & DateProps) {
  const safeTotal = Math.max(total, 1);
  return <><SubHeader title="正在提交" date={date} onDateChange={onDateChange} onBack={onBack} /><div className="run-status"><div className="run-ring"><b>{current}</b><span>/{total}</span></div><h2>{running ? `正在处理第 ${current} 单` : "任务已结束"}</h2><p>{message}</p><div className="progress-track"><i style={{ width: `${(current / safeTotal) * 100}%` }} /></div></div><section className="run-current"><div className="run-label">执行顺序 <StatusBadge status={running ? "待提交" : "已结束"} /></div><b>上传两张图片 → 关闭安检工单 → 写入流转日志</b><span>关闭成功但日志失败的工单可在记录页单独补发。</span><ol><li className="done">图片已由安卓原生层编码并上传</li><li className={running && !paused ? "working" : ""}>当前接口请求中</li><li>关闭安检工单</li><li>写入到访不遇日志</li></ol></section><section className="log-panel"><div>任务状态 <span>实时</span></div><p>{message}</p><p className="muted">所有工单按顺序串行执行，避免重复关闭。</p></section><div className="run-actions">{running ? <Button className="secondary-button" onPress={onTogglePause} isDisabled>{paused ? <><Icon name="play" size={16} />暂停功能准备中</> : <><Icon name="pause" size={16} />串行提交中</>}</Button> : <Button className="primary-button" onPress={onFinish}>查看提交记录</Button>}</div></>;
}

export function RecordsPage({ orders, date, onDateChange, onBack, onRetry }: { orders: WorkOrder[]; onBack: () => void; onRetry: (id: string) => void } & DateProps) {
  const closed = orders.filter((order) => order.status === "已结束").length;
  const logFailed = orders.filter((order) => order.status === "日志失败").length;
  return <><SubHeader title="提交记录" date={date} onDateChange={onDateChange} onBack={onBack} /><section className="record-summary"><div><b>{closed}</b><span>成功关闭</span></div><div><b className="warning-text">{logFailed}</b><span>待补发日志</span></div><div><b>{closed + logFailed}</b><span>本次处理</span></div></section><section className="record-list">{orders.filter((order) => order.status === "已结束" || order.status === "日志失败").map((order, index) => <article key={`${order.id}-${index}`}><div><b>{order.resident} · {order.unit}</b><span>{order.id} · 今天 {order.time.slice(0, 5)}</span></div><StatusBadge status={order.status} />{order.status === "日志失败" && <button className="retry-button" onClick={() => onRetry(order.id)}>补发日志</button>}</article>)}</section></>;
}
