import { Button } from "@heroui/react";
import type { WorkOrder } from "../types/workOrder";
import { Icon } from "../components/Icon";
import { PhotoTile } from "../components/PhotoTile";
import { SubHeader } from "../components/Navigation";
import { StatusBadge } from "../components/WorkOrderList";

type DateProps = { date: string; onDateChange: (value: string) => void };

export function PreparePage({ orders, activeOrder, pickedHistory, pickedLibrary, historyPhotos, date, onDateChange, onBack, onOpenGallery, onSelectOrder, onPickHistory, onCycleLibrary, onNext }: { orders: WorkOrder[]; activeOrder: WorkOrder; pickedHistory: string; pickedLibrary: string; historyPhotos: string[]; onBack: () => void; onOpenGallery: () => void; onSelectOrder: (id: string) => void; onPickHistory: (value: string) => void; onCycleLibrary: () => void; onNext: () => void } & DateProps) {
  return <><SubHeader title="准备照片" date={date} onDateChange={onDateChange} onBack={onBack} right={<button className="text-button" onClick={onOpenGallery}>图库管理</button>} /><div className="stepper"><span className="current">1</span><i /><span>2</span><i /><span>3</span><em>照片准备</em></div><section className="prepare-tabs">{orders.map((order, index) => <button key={`${order.id}-${index}`} onClick={() => onSelectOrder(order.id)} className={order.id === activeOrder.id ? "active" : ""}>{order.resident}<small>{order.unit}</small></button>)}</section><section className="prep-order"><p className="eyebrow">{activeOrder.id}</p><h2>{activeOrder.address}</h2><span>{activeOrder.resident} · {activeOrder.unit} · {activeOrder.time}</span></section><section className="section-block"><div className="section-heading"><div><h3>历史到访照片</h3><p>人工选择一张已验证的“到访不遇”照片</p></div><b>必选</b></div><div className="photo-grid">{historyPhotos.map((photo, index) => <PhotoTile key={photo} label={photo} tone={["gold", "blue", "purple"][index]} active={pickedHistory === photo} onClick={() => onPickHistory(photo)} />)}</div></section><section className="section-block"><div className="section-heading"><div><h3>本机图库补图</h3><p>从图库随机选取一张环境照片</p></div><button className="random-button" onClick={onCycleLibrary}>换一张</button></div><div className="photo-grid compact"><PhotoTile label={pickedLibrary} tone="green" active /></div></section><div className="page-action"><Button className="primary-button" onPress={onNext}>下一步：确认提交 <Icon name="chevron" size={17} /></Button></div></>;
}

export function ConfirmPage({ orders, reason, date, onDateChange, onBack, onReasonChange, onStart }: { orders: WorkOrder[]; reason: string; onBack: () => void; onReasonChange: (value: string) => void; onStart: () => void } & DateProps) {
  return <><SubHeader title="确认提交" date={date} onDateChange={onDateChange} onBack={onBack} /><div className="stepper"><span>1</span><i /><span className="current">2</span><i /><span>3</span><em>确认信息</em></div><section className="confirm-hero"><span>本次将串行处理</span><strong>{orders.length}</strong><b>个到访不遇工单</b><p>每单上传两张照片后关闭工单，再写入流转日志。</p></section><section className="confirm-list">{orders.map((order, index) => <article key={`${order.id}-${index}`}><div><b>{order.resident} · {order.unit}</b><span>{order.id}</span></div><div className="mini-photos"><PhotoTile label="历史" tone="gold" /><PhotoTile label="补图" tone="green" /></div></article>)}</section><section className="form-card"><label>流转人<input value="当前操作员" readOnly /></label><label>流转原因<input value={reason} onChange={(event) => onReasonChange(event.target.value)} /></label><label>备注<textarea defaultValue="现场到访未遇，门口有居住痕迹。" /></label></section><p className="safety-note">提交后不可撤销。关闭成功但日志失败时，系统只会补发日志，不会重复关闭。</p><div className="page-action"><Button className="primary-button" onPress={onStart}>开始串行提交 <Icon name="play" size={16} /></Button></div></>;
}

export function RunningPage({ total, paused, date, onDateChange, onBack, onTogglePause, onFinish }: { total: number; paused: boolean; onBack: () => void; onTogglePause: () => void; onFinish: () => void } & DateProps) {
  return <><SubHeader title="正在提交" date={date} onDateChange={onDateChange} onBack={onBack} /><div className="run-status"><div className="run-ring"><b>1</b><span>/{total}</span></div><h2>{paused ? "任务已暂停" : "正在处理第 1 单"}</h2><p>{paused ? "可以确认照片和网络后继续" : "正在上传第 1 张照片…"}</p><div className="progress-track"><i style={{ width: `${(1 / total) * 100}%` }} /></div></div><section className="run-current"><div className="run-label">当前工单 <StatusBadge status="待提交" /></div><b>张先生 · 2栋 1802</b><span>AJ202607120038</span><ol><li className="done">两张照片已校验</li><li className={!paused ? "working" : ""}>上传照片中</li><li>关闭安检工单</li><li>写入到访不遇日志</li></ol></section><section className="log-panel"><div>任务日志 <span>实时</span></div><p>10:18:07　开始处理 AJ202607120038</p><p>10:18:09　照片 1/2 已加入上传队列</p><p className="muted">下一单将在完成后随机等待 20–40 秒</p></section><div className="run-actions"><Button className="secondary-button" onPress={onTogglePause}>{paused ? <><Icon name="play" size={16} />继续任务</> : <><Icon name="pause" size={16} />暂停任务</>}</Button><Button className="primary-button" onPress={onFinish}>演示完成</Button></div></>;
}

export function RecordsPage({ orders, date, onDateChange, onBack, onRetry }: { orders: WorkOrder[]; onBack: () => void; onRetry: (id: string) => void } & DateProps) {
  return <><SubHeader title="提交记录" date={date} onDateChange={onDateChange} onBack={onBack} /><section className="record-summary"><div><b>4</b><span>成功关闭</span></div><div><b className="warning-text">1</b><span>待补发日志</span></div><div><b>5</b><span>本次处理</span></div></section><section className="record-list">{orders.filter((order) => order.status === "成功" || order.status === "日志失败").map((order, index) => <article key={`${order.id}-${index}`}><div><b>{order.resident} · {order.unit}</b><span>{order.id} · 今天 {order.time.slice(0, 5)}</span></div><StatusBadge status={order.status} />{order.status === "日志失败" && <button className="retry-button" onClick={() => onRetry(order.id)}>补发日志</button>}</article>)}</section></>;
}
