import type { DrawerKind, Theme, WorkOrder } from "../types/workOrder";
import { Icon } from "./Icon";
import { PhotoTile } from "./PhotoTile";
import { StatusBadge } from "./WorkOrderList";

export function AppDrawer({ type, order, theme, libraryPhotos, setTheme, onClose, onLogout }: { type: DrawerKind; order: WorkOrder; theme: Theme; libraryPhotos: string[]; setTheme: (value: Theme) => void; onClose: () => void; onLogout: () => void }) {
  const titles = { detail: "工单详情", gallery: "本机图库", settings: "会话与显示" };
  return <div className="drawer-overlay" onClick={onClose}><section className="drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-handle" /><header><h2>{titles[type]}</h2><button className="icon-button" onClick={onClose}><Icon name="close" /></button></header>{type === "detail" && <div className="drawer-content detail-content"><StatusBadge status={order.status} /><h3>{order.resident} · {order.unit}</h3><section className="detail-address"><span>服务地址</span><b>{order.address}</b></section><dl><div><dt>工单号</dt><dd>{order.id}</dd></div><div><dt>预约时间</dt><dd>{order.time}</dd></div><div><dt>服务对象</dt><dd>{order.resident}</dd></div><div><dt>工单状态</dt><dd><StatusBadge status={order.status} /></dd></div><div><dt>处理类型</dt><dd>到访不遇</dd></div></dl><section className="detail-note"><span>处理说明</span><p>请确认现场情况后，在提交页选择历史照片和补图，再执行批量流转。</p></section></div>}{type === "gallery" && <div className="drawer-content"><p className="drawer-tip">共 4 张本机图片，仅用于为当前工单随机补图。</p><div className="gallery-grid">{libraryPhotos.map((photo, index) => <PhotoTile key={photo} label={photo} tone={["green", "blue", "purple", "gold"][index]} />)}<button className="add-photo"><Icon name="plus" /><span>导入图片</span></button></div></div>}{type === "settings" && <div className="drawer-content"><section className="settings-block"><span>显示主题</span><div className="theme-select">{(["system", "light", "dark"] as Theme[]).map((item) => <button key={item} className={theme === item ? "active" : ""} onClick={() => setTheme(item)}>{item === "system" ? "跟随系统" : item === "light" ? "浅色" : "深色"}</button>)}</div></section><section className="settings-block session"><span>当前会话</span><b>已登录 · 操作员</b><p>登录信息仅保存在此设备，退出后将立即清除。</p><button className="logout-button" onClick={onLogout}><Icon name="logout" size={17} />退出登录</button></section></div>}</section></div>;
}
