import {
  BarChart3,
  Calendar,
  CalendarClock,
  Camera,
  Check,
  ClipboardCheck,
  Copy,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  Clock3,
  Database,
  Download,
  Ellipsis,
  FileText,
  Home,
  ListTodo,
  LogOut,
  Pause,
  Pin,
  Play,
  Plus,
  RefreshCw,
  Search,
  ScanQrCode,
  Send,
  Settings,
  SlidersHorizontal,
  Star,
  Trash2,
  Upload,
  X,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  calendar: Calendar,
  appointment: CalendarClock,
  camera: Camera,
  chart: BarChart3,
  check: Check,
  audit: ClipboardCheck,
  chevron: ChevronRight,
  collapse: ChevronsUp,
  clock: Clock3,
  close: X,
  copy: Copy,
  database: Database,
  download: Download,
  expand: ChevronsDown,
  filter: SlidersHorizontal,
  home: Home,
  logout: LogOut,
  more: Ellipsis,
  note: FileText,
  pause: Pause,
  pin: Pin,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  scan: ScanQrCode,
  send: Send,
  settings: Settings,
  star: Star,
  tasks: ListTodo,
  trash: Trash2,
  upload: Upload,
};

export function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const Glyph = icons[name] ?? Check;
  return <Glyph className="icon" size={size} strokeWidth={1.9} aria-hidden="true" />;
}
